theme = "showfolio"
languageCode = "en-us"
baseurl = "https://gmex.global"
title = "GMEX"
enableRobotsTXT = true

[params]
  name = "Showfolio Theme"
  description = "Modern portfolio theme for your Hugo site."
  author = "John Doe"
  authorEmail = "name@example.com"
  authorImage = "/White_icon.svg"
  autoDarkMode = true

  copyright = "Copyright © 2021 - John Doe · All rights reserved"
  favicon = "/B_icon.ico"

[params.homepage]
  title = "GMEX: Empowering Your Financial Future"
  tagline = "🚧 Under Construction"
  description = "Please bear with us as we embark on a turbo-charged, caffeine-fueled marathon to bring this system to life!"
  contact = "mailto:admin+prelaunch@gmex.global"

[params.homepage.social]
  facebook = "https://www.facebook.com/profile.php?id=61550640038309"
  twitter = "https://twitter.com/GMEX_Global"
  medium = "https://medium.com/@gmexglobal"
  telegram = "https://t.me/GMEXGlobal"
  tiktok = "https://www.tiktok.com/@gmexglobal"